### ISSUE TITLE
Write Section 4: Discussion

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/LocalGroupHaloProps#80]
@marxwillia has laid out a nice plan, it just needs filling out. Marc, have you made progress on this offline, and just need to git push? If you have no time, let us know and we can take on the subsections between us:

* [x] 4.1 Comparison with the Timing Argument #86 
* [x] 4.2 Mass of the Milky Way #87 
* [x] 4.3 Mass of the LMC #88 
* [x] 4.4 Uses and Limitations of the GMM Approach (review) #89

**Comment by marxwillia** [comment]
All sections written.  Further issues should be edits/rewrites.
